config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, except: [ :new, :create ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, presence: true
  validates_inclusion_of :category, :in => ["chinese", "italian", "japanese", "french", "belgian"]

  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.save
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: (0..5) }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    Restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(params[:restaurant_id])
    else
      render :new
    end
  end

  def edit
  end

  def update
    @review.update(review_params)
    redirect_to restaurant_path
  end

  def destroy
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class= "col-sm-6 col-sm-offset-3">
  <h1><%= "#{ @restaurant.new_record?() ? 'Add a new restaurant' : "Edit the restaurant: #{@restaurant.name}" }" %></h1>
  <div class="container col-sm-12">
    <%= simple_form_for(@restaurant) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
      </div>
      <%= link_to "Back", "#{ @restaurant.new_record?() ? restaurants_path : restaurant_path }", class: "btn btn-warning" %>
      <%= f.submit class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class= "col-sm-6 col-sm-offset-3">
  <h1>List of Restaurants</h1>
  <div>
    <ul>
      <% @restaurants.each do |restaurant| %>
        <div>
            <li><%= link_to restaurant.name, "/restaurants/#{restaurant.id}" %></li>
        </div>
      <% end %>
    </ul>
    <%= link_to "Add restaurant", new_restaurant_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<div class= "col-sm-6 col-sm-offset-3">
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <p><%= "Category: #{@restaurant.category}" %></p>
  <h3>Reviews</h3>
  <div>
    <ul>
      <% @restaurant.reviews.each do |review| %>
        <div>
            <li><%= "#{review.content} (#{review.rating}*)" %></li>
        </div>
      <% end %>
    </ul>
    <%= link_to "+ Add review", new_restaurant_review_path(@restaurant.id) %>
  </div>
  <br>
  <div>
    <%= link_to "Back to list", restaurants_path, class: "btn btn-warning" %>
    <%= link_to "Edit", edit_restaurant_path, class: "btn btn-primary" %>
    <%= link_to "Delete",  restaurant_path,  method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>

app/views/reviews/_form.html.erb
<div class= "col-sm-6 col-sm-offset-3">
  <h1><%= "#{ @review.new_record?() ? 'Add a new review' : "Edit the review: #{@review.content}" }" %></h1>
  <div class="container col-sm-12">
    <%= simple_form_for [@restaurant, @review] do |f| %>
      <div class="form-group">
        <%= f.input :content, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
      </div>
      <%= link_to "Back", restaurant_path(@restaurant.id), class: "btn btn-warning" %>
      <%= f.submit class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/reviews/edit.html.erb
<%= render 'form', review: @review %>

app/views/reviews/new.html.erb
<%= render 'form', review: @review %>